-- begin CUBAPETCLINIC_PET
alter table CUBAPETCLINIC_PET add constraint FK_CUBAPETCLINIC_PET_TYPE foreign key (TYPE_ID) references CUBAPETCLINIC_PET_TYPE(ID)^
alter table CUBAPETCLINIC_PET add constraint FK_CUBAPETCLINIC_PET_OWNER foreign key (OWNER_ID) references CUBAPETCLINIC_OWNER(ID)^
create index IDX_CUBAPETCLINIC_PET_TYPE on CUBAPETCLINIC_PET (TYPE_ID)^
create index IDX_CUBAPETCLINIC_PET_OWNER on CUBAPETCLINIC_PET (OWNER_ID)^
create index IDX_CUBAPETCLINIC_PET on CUBAPETCLINIC_PET (NAME) ^
-- end CUBAPETCLINIC_PET
-- begin CUBAPETCLINIC_VET
create index IDX_CUBAPETCLINIC_VET on CUBAPETCLINIC_VET (LAST_NAME) ^
-- end CUBAPETCLINIC_VET
-- begin CUBAPETCLINIC_OWNER
create index IDX_CUBAPETCLINIC_OWNER on CUBAPETCLINIC_OWNER (LAST_NAME) ^
-- end CUBAPETCLINIC_OWNER
-- begin CUBAPETCLINIC_VISIT
alter table CUBAPETCLINIC_VISIT add constraint FK_CUBAPETCLINIC_VISIT_PET foreign key (PET_ID) references CUBAPETCLINIC_PET(ID)^
create index IDX_CUBAPETCLINIC_VISIT_PET on CUBAPETCLINIC_VISIT (PET_ID)^
-- end CUBAPETCLINIC_VISIT
-- begin CUBAPETCLINIC_VET_SPECIALITY
alter table CUBAPETCLINIC_VET_SPECIALITY add constraint FK_VETSPE_VET foreign key (VET_ID) references CUBAPETCLINIC_VET(ID)^
alter table CUBAPETCLINIC_VET_SPECIALITY add constraint FK_VETSPE_SPECIALITY foreign key (SPECIALITY_ID) references CUBAPETCLINIC_SPECIALITY(ID)^
-- end CUBAPETCLINIC_VET_SPECIALITY
